program: secure_house.sh #this is dumb, you dont need this for bash script. but the test.sh requires it exit with code 0, so VIOLA !
	@cp secure_house.sh secure_house
	@chmod +x secure_house # add executible to our executable
	@echo "Build Success"